name: Deploy via SCP

on:
  push:
    branches:
      - main  # Se ejecuta al subir cambios a la rama main

jobs:
  network-test:
    runs-on: ubuntu-latest
    steps:
      - name: Probar conectividad al puerto 22
        run: |
          echo "Intentando conectar a ${{ secrets.SERVER }}..."
          # nc (netcat) verifica si el puerto está abierto
          nc -zv -w 5 ${{ secrets.SERVER }} 22
          
      - name: Verificar huella SSH (Fingerprint)
        run: |
          # Esto intenta obtener la llave pública del servidor
          ssh-keyscan -p 22 ${{ secrets.SERVER }}
