name: Deploy via SCP

on:
  push:
    branches:
      - main  # Se ejecuta al subir cambios a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v1

      - name: Copiar archivos vía SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH }}
          passphrase: ${{ secrets.PW_SECRET }}
          port: 22
          target: "/sdf/udd/a/apena/html"    # Carpeta destino en el servidor
